export enum PageLayoutType {
  CLIENT = 'CLIENT',
  ADMIN = 'ADMIN',
  ADMIN_AUTH = 'ADMIN_AUTH',
  CLIENT_PUBLIC = 'CLIENT_PUBLIC',
  ADMIN_EDIT = 'ADMIN_EDIT',
  ADMIN_PREVIEW_PAGE = 'ADMIN_PREVIEW_PAGE',
  PUBLIC_CMS_ROUTE = 'PUBLIC_CMS_ROUTE',
}
