export enum ReducerName {
  LAYOUT = 'layout',
  CRUD_LAYOUT = 'crudLayout',
  CLIENT_AUTH = 'clientAuth',
  CLIENT_UPLOAD = 'clientUpload',
  CLIENT_SHAPEFILE = 'clientShapeFile',
  ADMIN_AUTH = 'adminAuth',
  CLIENT_PUBLIC = 'clientPublic',
  ADMIN_UPLOAD = 'adminUpload',
  ADMIN_CLIENT_USER = 'adminClientUser',
  ADMIN_SETTING = 'adminSetting',
  ADMIN_CUSTOM_PAGE = 'adminCustomPage',
  ICON_SELECT = 'iconSelect',
  FILE_SELECT = 'fileSelect',
  ADMIN_ADMIN_USER = 'adminAdminUser',
  ADMIN_ARTICLES = 'adminArticles',
  ADMIN_CAROUSES = 'adminCarouses',
  ADMIN_ARTICLES_CATEGORY = 'adminArticlesCategory',
  PRODUCT = 'product',
}
